version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing required packages
      - yum update -y
      - yum install -y jq
  
  build:
    commands:
      - echo "Identifying migration files..."
      - MIGRATION_FILES=$(find migrations -type f -name "*.sql" | sort)
      - |
        if [ -z "$MIGRATION_FILES" ]; then
          echo "No SQL migration files found."
          exit 0
        fi
      
      - echo "Found the following migration files:"
      - echo "$MIGRATION_FILES"
      
      - echo "Creating metadata file for execution..."
      - |
        cat > migrations-metadata.json << EOMETA
        {
          "migrationFiles": [
            $(for file in $MIGRATION_FILES; do echo "\"$file\","; done | sed '$s/,$//')
          ],
          "timestamp": "$(date +%Y%m%d%H%M%S)",
          "buildId": "$CODEBUILD_BUILD_ID"
        }
        EOMETA
      
      - echo "Skipping SQL validation - will be handled by Lambda"
  
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - migrations/**/*
    - migrations-metadata.json
    - buildspec.yml
  discard-paths: no